services:
  - type: web
    name: social-media-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: social-media-backend-db
          property: connectionString
      - key: LOG_LEVEL
        value: info

databases:
  - name: social-media-backend-db
    plan: free
